const menuButton=document.querySelector('.menu-toggle');
const navLinks=document.querySelector('#nav-links');
if(menuButton&&navLinks){menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu')});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}))}
const root=document.documentElement;const themeButton=document.querySelector('.theme-toggle');
const dark={'--bg':'#090b0f','--panel':'#10141a','--panel-2':'#151b22','--text':'#f2f4f7','--muted':'#9aa4b2','--line':'#252c35','--accent':'#63e6be','--accent-2':'#74c0fc'};
const light={'--bg':'#f6f7f9','--panel':'#fff','--panel-2':'#eef1f5','--text':'#11151b','--muted':'#596575','--line':'#dfe4ea','--accent':'#087f5b','--accent-2':'#1971c2'};
function applyTheme(mode){Object.entries(mode==='light'?light:dark).forEach(([k,v])=>root.style.setProperty(k,v));root.dataset.theme=mode;if(themeButton){themeButton.firstElementChild.textContent=mode==='light'?'☀':'◐';themeButton.setAttribute('aria-label',mode==='light'?'Activer le thème sombre':'Activer le thème clair')}try{localStorage.setItem('portfolio-theme',mode)}catch(e){}}
if(themeButton){let saved=null;try{saved=localStorage.getItem('portfolio-theme')}catch(e){}applyTheme(saved||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));themeButton.addEventListener('click',()=>applyTheme(root.dataset.theme==='light'?'dark':'light'))}
const revealItems=document.querySelectorAll('.reveal');revealItems.forEach(el=>el.classList.add('js-ready'));
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});revealItems.forEach(el=>observer.observe(el))}else{revealItems.forEach(el=>el.classList.add('visible'))}
const header=document.querySelector('.header');if(header)window.addEventListener('scroll',()=>{header.style.boxShadow=scrollY>10?'0 14px 40px rgba(0,0,0,.16)':'none'},{passive:true});